### ISSUE TITLE
Colab Notebook not found

### ISSUE THREAD

**Issue by jianjunwu** [vijishmadhavan/ArtLine#12]
FYI

**Comment by vijishmadhavan** [comment]
https://colab.research.google.com/github/vijishmadhavan/Light-Up/blob/master/ArtLine(AR).ipynb

**Comment by jianjunwu** [comment]
thanks

**Comment by vijishmadhavan** [comment]
Check my new project.
https://github.com/vijishmadhavan/Toon-Me
