### ISSUE TITLE
No such colab notebook

### ISSUE THREAD

**Issue by chengweiv5** [vijishmadhavan/ArtLine#20]
## Getting Started Yourself

The easiest way to get started is to simply try out on Colab: https://colab.research.google.com/github/vijishmadhavan/Light-Up/blob/master/ArtLine(Try_it_on_Colab).ipynb

seems the notebook name changed but it hasn't been updated in the doc above.

Thanks.

**Comment by chengweiv5** [comment]
here are all 4 notebook listed in colab

![20210119110554](https://user-images.githubusercontent.com/689798/104982813-685bf680-5a46-11eb-99a8-c896af92170f.png)

**Comment by vijishmadhavan** [comment]
Try this

https://colab.research.google.com/github/vijishmadhavan/Light-Up/blob/master/ArtLine(AR).ipynb

Also check  Toon-Me

https://github.com/vijishmadhavan/Toon-Me

**Comment by chengweiv5** [comment]
OK，thanks.
